# Default values for generic-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

openshift: true
replicaCount: 1
image:
  ## tag: latest (check image tag pushed by pipeline service after build)
  tag:
  ## One of two is REQUIRED: either image.repository or image.stream
  ## repository: .e.g. nexus.elm.sa/zaw-snapshots/myapp
  ##             Useful if the image is outside the internal
  ##             registry of the OCP cluster (e.g. dev, qa)
  ##        (check image repo pushed by pipeline service after build)
  repository:
  ## pullSecret: if repository is private, use pullSecret
  ##             defaults to nexus
  pullSecret: 'nexus'
  ## imagestream - relative to the Cluster where resources will be deployed
  ##               useful if the image is inside the internal
  ##               registry of the OCP cluster (.e.g staging, prod)
  ##   for example, if the image is availabe in OCP internal registry under
  ##    this name: "registry.rnd-apps.elm.sa/elm-images/myapp:v1.0.0"
  ##    then: 
  # stream:
  #   name: myapp
  #   namespace: elm-images
  stream:
    ## imagestream resource name
    name:
    ## namespace like: elm-images or openshift : depends where is your imagestream
    ## it defaults to namespace of the RELEASE
    namespace:

nexus:
  host: nexus.elm.sa
  fullnameOverride: nexus

deployment:
  revisionHistoryLimit: 5
  triggers:
    imageStreamChange: true

port: 8080
extraPorts: []
route:
  enabled: false
  ## domain: dev-apps.elm.sa
  domain:
  host:
  extraHosts: []

####
# envVars:
#   SPRING_LOCATION_CONFIG: /opt/app.yaml
#   SMS_API_PASSWORD: xBlah
envVars: {}
####
configFile:
  name: # application.properties
  content: #
  mount: # /opt/app
  ## example of config file content
  # content: |
  #   spring.appName = myapp
  #   spring.context = /

serviceAccount:
  ## Specifies whether a service account should be created
  create: false
  ## Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi
securityContext: {}
rollout:
  resources: {}
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nameOverride: ""
fullnameOverride: ""

nodeSelector: {}

tolerations: []

affinity: {}
