{{- if .Values.apm.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: apm-{{ include "web-app.fullname" . }}
  labels:
    {{- include "web-app.labels" . | nindent 4 }}
data:
  ELASTIC_APM_SECRET_TOKEN: {{ .Values.apmProvider.token }}
{{- end }}