{{- if and .Values.sshd.monitoring.enabled .Values.sshd.monitoring.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "docker-daemon-sshd.fullname" . }}-sshd
  labels:
    {{- include "docker-daemon-sshd.labels" . | nindent 4 }}
    {{- with .Values.sshd.monitoring.serviceMonitor.selector }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  namespace: {{ .Values.sshd.monitoring.serviceMonitor.namespace }}
spec:
  endpoints:
  - interval: {{ .Values.sshd.monitoring.serviceMonitor.interval }}
    path: {{ .Values.sshd.monitoring.serviceMonitor.path }}
    {{- if not (eq .Values.monitoring.port .Values.sshd.monitoring.port) }}
    port: metrics-sshd
    {{- else }}
    port: metrics
    {{- end }}
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{- include "docker-daemon-sshd.selectorLabels" . | nindent 6 }}
{{- end }}