apiVersion: v1
kind: Service
metadata:
  name: {{ include "prometheus-to-msteams.fullname" . }}
  labels:
{{ include "prometheus-to-msteams.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8089
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "prometheus-to-msteams.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
