apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "radius-server.fullname" . }}
  labels:
    {{- include "radius-server.labels" . | nindent 4 }}
data:
  clients.conf: |
    client healthcheker {
      ipaddr = 127.0.0.1/32
      secret = healthsecret
    }
    {{ .Values.authorization.clients | nindent 4 }}
  users: |
    healthuser Cleartext-Password := "healthpass", MS-CHAP-Use-NTLM-Auth := 0
    {{ .Values.authorization.users | nindent 4 }}

 