apiVersion: v1
kind: Service
metadata:
  name: {{ include "radius-server.fullname" . }}
  labels:
    {{- include "radius-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: radius
      name: radius
    - port: {{ .Values.service.portAuth }}
      targetPort: radius-auth
      protocol: UDP
      name: radius-auth
    - port: {{ .Values.service.portAcc }}
      targetPort: radius-acc
      protocol: UDP
      name: radius-acc
  selector:
    {{- include "radius-server.selectorLabels" . | nindent 4 }}
