---
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "docker-daemon-sshd.fullname" . }}-helper-scripts
  labels:
    {{- include "docker-daemon-sshd.labels" . | nindent 4 }}
data:
{{- with .Files.Glob "files/scripts/*.sh" }}
{{ tpl .AsConfig $ | indent 2 }}
{{- end }}

