{{- if .Values.existingDockerDaemon.enabled }}
---
kind: Endpoints
apiVersion: v1
metadata:
  name: {{ include "docker-daemon-sshd.fullname" . }}
  labels:
    {{- include "docker-daemon-sshd.labels" . | nindent 4 }}
subsets:
 - addresses:
    - ip: {{ .Values.existingDockerDaemon.ip  }}
   ports:
    - name: sshd
      port: {{ .Values.existingDockerDaemon.port }}
      protocol: TCP
{{- if .Values.monitoring.enabled }}
    - name: metrics
      port: {{ .Values.monitoring.port }}
      protocol: TCP
  {{- end }}
{{- if and .Values.sshd.monitoring.enabled (not (eq .Values.monitoring.port .Values.sshd.monitoring.port)) }}
    - name: metrics-sshd
      port: {{ .Values.sshd.monitoring.port }}
      protocol: TCP
{{- end }}
{{- end }}