---
kind: Secret
apiVersion: v1
metadata:
  name: {{ include "docker-dind-sshd.fullname" . }}-ssh-dir
  labels:
    {{- include "docker-dind-sshd.labels" . | nindent 4 }}
data:
  id_rsa.pub: {{ .Values.sshKeys.public | b64enc }}
