{{- if not .Values.existingDockerDaemon.enabled }}
{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "docker-daemon-sshd.serviceAccountName" . }}
  labels:
    {{- include "docker-daemon-sshd.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}