{{- if eq .Values.deployment.kind "DeploymentConfig" }}
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: {{ include "single-page-app.fullname" . }}
  labels:
    {{- include "single-page-app.labels" . | nindent 4 }}
spec:
  dockerImageRepository: {{ include "single-page-app.imageRepo" . }}
  tags:
    - name: {{ (include "single-page-app.imageTag" .) | quote }}
      from:
        kind: DockerImage
        name: '{{ include "single-page-app.imageRepo" . }}:{{ include "single-page-app.imageTag" . }}'
  lookupPolicy:
    local: false
{{- end }}