{{- with .Values.envVars }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "single-page-app.fullname" $ }}-env-vars
  labels:
    {{- include "single-page-app.labels" $ | nindent 4 }}
data:
{{- range $key, $value:= . }}
  {{ $key }}: {{ $value | toString | b64enc }}
{{- end }}
{{- end }}



{{/*
# process .env file
{{- range $line := splitList "\n" .Values.envFile }}
  {{- $kv := splitList "=" $line -}}
  {{- $k := first $kv -}}
  {{- if $k }}
  {{ $k }}: {{ last $kv | b64enc | quote }}
  {{- end }}

{{- end }}
# process .env file which extends and overrides
{{- if .Values.extraEnvFile }}
{{- range $line := splitList "\n" .Values.extraEnvFile }}
  {{- $kv := splitList "=" $line -}}
  {{- $k := first $kv -}}
  {{- if $k }}
  {{ $k }}: {{ last $kv | b64enc | quote }}
  {{- end }}

{{- end }}
{{- end }}

*/}}