static_resources:
  listeners:
  - address:
      socket_address:
        address: 0.0.0.0
        port_value: {{ .Values.proxyPorts.webPort }}
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          codec_type: AUTO
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: app
              domains:
              - "*"
              routes:
              - match:
                  prefix: "/"
                route:
                  cluster: {{ include "service-proxy.fullname" . }}
                  auto_host_rewrite: true
                  internal_redirect_policy:
                    max_internal_redirects: 10
                    redirect_response_codes:
                    - 301
                    - 302
                    predicates:
                    - name: envoy.internal_redirect_predicates.safe_cross_scheme
                      typed_config:
                        '@type': type.googleapis.com/envoy.extensions.internal_redirect.safe_cross_scheme.v3.SafeCrossSchemeConfig
                    allow_cross_scheme_redirect: false
          http_filters:
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router

  clusters:
  - name: {{ include "service-proxy.fullname" . }}
    type: STRICT_DNS
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: {{ include "service-proxy.fullname" . }}
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: {{ required "Backend Service ADDRESS is Required" .Values.backendService.address }}
                port_value: {{ .Values.backendService.port }}
    transport_socket:
      name: envoy.transport_sockets.tls
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
        {{- if (include "service-proxy.backendServiceHasCaCert" .) }}
        common_tls_context:
          validation_context:
            match_typed_subject_alt_names:
            - san_type: DNS
              matcher:
                exact: {{ .Values.backendService.address }}
            trusted_ca:
              filename: /tmp/certs/backend-ca.crt
        {{- end }}

admin:
  access_log_path: "/dev/null"
  address:
    socket_address:
      address: 0.0.0.0
      port_value: {{ .Values.proxyPorts.adminPort }}