static_resources:
  listeners:
  - address:
      socket_address:
        address: 0.0.0.0
        port_value: {{ .Values.proxyPorts.webPort }}
    filter_chains:
    - filters:
      - name: envoy.filters.network.tcp_proxy
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
          cluster: {{ include "service-proxy.fullname" . }}
          stat_prefix: https_passthrough

  clusters:
  - name: {{ include "service-proxy.fullname" . }}
    type: STRICT_DNS
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: {{ include "service-proxy.fullname" . }}
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address:  {{ required "Backend Service ADDRESS is Required" .Values.backendService.address }}
                port_value: {{ .Values.backendService.port }}
    transport_socket:
      name: envoy.transport_sockets.tls
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
        sni: {{ .Values.backendService.address }}
admin:
  access_log_path: "/dev/null"
  address:
    socket_address:
      address: 0.0.0.0
      port_value: {{ .Values.proxyPorts.adminPort }}