static_resources:
  listeners:
  - name: redis_listener
    address:
      socket_address:
        address: 0.0.0.0
        port_value: {{ .Values.proxyPorts.webPort }}
    filter_chains:
    - filters:
      - name: envoy.filters.network.redis_proxy
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.redis_proxy.v3.RedisProxy
          stat_prefix: egress_redis
          settings:
            op_timeout: 5s
          prefix_routes:
            catch_all_route:
              cluster: {{ include "service-proxy.fullname" . }}
  clusters:
  - name: {{ include "service-proxy.fullname" . }}
    type: STRICT_DNS  # static
    lb_policy: MAGLEV
    load_assignment:
      cluster_name: {{ include "service-proxy.fullname" . }}
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: {{ required "Redis Backend Service ADDRESS is Required" .Values.backendService.address }}
                port_value: {{ .Values.backendService.port }}
admin:
  access_log_path: "/dev/null"
  address:
    socket_address:
      address: 0.0.0.0
      port_value: {{ .Values.proxyPorts.adminPort }}