{{ if .Values.serviceAccount.privileged }}
{{ if .Values.serviceAccount.create }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ printf "privileged-scc-%s" ( include "web-app.fullname" . ) }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "web-app.labels" . | nindent 4 }}
rules:
- apiGroups:
  - security.openshift.io
  resourceNames:
  - privileged
  resources:
  - securitycontextconstraints
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ printf "privileged-scc-%s" ( include "web-app.fullname" . ) }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ printf "privileged-scc-%s" ( include "web-app.fullname" . ) }}
subjects:
- kind: ServiceAccount
  name: {{ include "web-app.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{ else }}
{{- printf "\n serviceAccount.privileged=true requires non-default serviceAccount. Fix it by setting serviceAccount.create=true" | fail -}}
{{ end }}
{{ end }}