{{- if .Values.configFile.name -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "web-app.fullname" . }}-file
  labels:
    {{- include "web-app.labels" . | nindent 4 }}
{{- if eq (include "web-app.is-job" . ) "true" }}
  annotations:
    {{- toYaml .Values.job.annotations | nindent 4 }}
{{- end }}
data:
  {{ .Values.configFile.name }}: |
    {{- tpl .Values.configFile.content . | nindent 4 }}
{{- end }}