{{ if .Values.deployment.enabled }}
{{- if eq .Values.deployment.kind "DeploymentConfig" }}
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: {{ include "web-app.fullname" . }}
  labels:
    {{- include "web-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.deployment.revisionHistoryLimit }}
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: {{ .Values.deployment.triggers.imageStreamChange }}
      containerNames:
      - {{ include "web-app.fullname" . }}
      from:
        kind: ImageStreamTag
        name: {{ printf "%s:%s" (include "web-app.fullname" .) .Values.image.tag }}
    type: ImageChange
  selector:
    {{- include "web-app.labels" . | nindent 4 }}
    deploymentconfig: {{ include "web-app.fullname" . }}
  strategy:
    activeDeadlineSeconds: 21600
    resources:
      {{- toYaml .Values.rollout.resources | nindent 6 }}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      labels:
        {{- include "web-app.labels" . | nindent 8 }}
        deploymentconfig: {{ include "web-app.fullname" . }}
      annotations:
      {{- if .Values.envVars }}
        checksum/configenvvars: {{ include (print $.Template.BasePath "/secret-env-vars.yaml") . | sha256sum }}
      {{- end }}
      {{- if .Values.envVarsSealed }}
        checksum/configenvvarssealed: {{ include (print $.Template.BasePath "/secret-env-vars-sealed.yaml") . | sha256sum }}
      {{- end }}
      {{- if .Values.configFile.name }}
        checksum/configfile: {{ include (print $.Template.BasePath "/configmap-file.yaml") . | sha256sum }}
      {{- end }}
    spec:
      {{- include "web-app.pod" . | nindent 6 -}}
  test: false
{{- end }}
{{- end }}