{{- if .Values.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "web-app.fullname" . }}
  labels:
    {{- include "web-app.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    {{- if eq .Values.deployment.kind "DeploymentConfig" }}
    apiVersion: apps.openshift.io/v1
    {{- else }}
    apiVersion: apps/v1
    {{- end }}
    kind: {{ .Values.deployment.kind }}
    name: {{ include "web-app.fullname" . }}
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: {{ .Values.autoscaling.targetMemoryUtilizationPercentage }}
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        # TODO : auto-default it based on env ( prod=50 , dev=85)
        averageUtilization: {{ .Values.autoscaling.targetCPUUtilizationPercentage }}
        # type: AverageValue
        # averageValue: 500m
{{- end }}
