{{- if eq .Values.deployment.kind "DeploymentConfig" }}
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: {{ include "web-app.fullname" . }}
  labels:
    {{- include "web-app.labels" . | nindent 4 }}
spec:
  dockerImageRepository: {{ include "web-app.imageRepo" . }}
  tags:
    - name: {{ .Values.image.tag | quote }}
      from:
        kind: DockerImage
        name: '{{ include "web-app.imageRepo" . }}:{{ .Values.image.tag }}'
  lookupPolicy:
    local: false
{{- end }}