{{- if eq .Values.deployment.kind "DeploymentConfig" }}
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: {{ include "webapp.fullname" . }}
  labels:
    {{- include "webapp.labels" . | nindent 4 }}
spec:
  dockerImageRepository: {{ include "webapp.imageRepo" . }}
  tags:
    - name: {{ (include "webapp.imageTag" .) | quote }}
      from:
        kind: DockerImage
        name: '{{ include "webapp.imageRepo" . }}:{{ include "webapp.imageTag" . }}'
  lookupPolicy:
    local: false
{{- end }}