{{- if and (not .Values.openshift) .Values.route.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "web-app.fullname" $ }}
  {{- with .Values.route.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "web-app.labels" . | nindent 4 }}
spec:
  rules:
  {{- range $index,$host := ( splitList "@" (include "web-app.hosts" . )) }}
  - host: {{ $host }}
    http:
      paths:
      - backend:
          service:
            name: {{ include "web-app.fullname" $ }}
            port:
              name: tcp-{{ $.Values.port }}
        pathType: ImplementationSpecific
        path: {{ $.Values.route.path }}
  {{- end -}}
{{- end -}}