apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "web-app.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "web-app.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.replicaMinAvailable }}
  selector:
    matchLabels:
      {{- include "web-app.selectorLabels" . | nindent 6 }}