{{ if .Values.extraPersistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "webapp.fullname" . }}-extra
  labels:
    {{- include "webapp.labels" . | nindent 4 }}
  # finalizers:
  # - kubernetes.io/pvc-protection
spec:
{{- if .Values.extraPersistence.volumeName }}
  volumeName: {{ .Values.extraPersistence.volumeName }}
{{- end }}
  accessModes:
  - {{ .Values.extraPersistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.extraPersistence.size }}
{{- if .Values.extraPersistence.storageClass }}
{{- if (eq "-" .Values.extraPersistence.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.extraPersistence.storageClass }}"
{{- end }}
{{- end }}
{{ end }}
