{{- if eq (include "web-app.is-statefulset" . ) "false" }}
{{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "web-app.fullname" . }}
  labels:
    storage.{{ .Values.companyDomain }}/class: '{{ default "default" (ternary "default" .Values.persistence.storageClass (eq .Values.persistence.storageClass "-")) }}'
    {{- include "web-app.labels" . | nindent 4 }}
  # finalizers:
  # - kubernetes.io/pvc-protection
spec:
{{- if .Values.persistence.volumeName }}
  volumeName: {{ .Values.persistence.volumeName }}
{{- end }}
  accessModes:
  - {{ .Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
{{- if .Values.persistence.storageClass }}
{{- if (eq "-" .Values.persistence.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.persistence.storageClass }}"
{{- end }}
{{- end }}
{{- end }}
{{- end }}