{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "web-app.serviceAccountName" . }}
  labels:
    {{- include "web-app.labels" . | nindent 4 }}
  {{- if eq (include "web-app.is-job" . ) "true" }}
  annotations:
    {{- toYaml .Values.job.annotations | nindent 4 }}
  {{- end -}}
{{- end }}
