{{- if .Values.deployment.enabled }}
{{- if eq (include "web-app.is-statefulset" . ) "true" }}
apiVersion: "apps/v1"
kind: StatefulSet
metadata:
  name: {{ include "web-app.fullname" . }}
  labels:
    {{- include "web-app.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "web-app.fullname" . }}-headless
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  updateStrategy:
    type: {{ .Values.rollout.type }}
  selector:
     matchLabels:
      {{- include "web-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
      {{- if .Values.envVars }}
        checksum/configenvvars: {{ include (print $.Template.BasePath "/secret-env-vars.yaml") . | sha256sum }}
      {{- end }}
      {{- if .Values.envVarsSealed }}
        checksum/configenvvarssealed: {{ include (print $.Template.BasePath "/secret-env-vars-sealed.yaml") . | sha256sum }}
      {{- end }}
      {{- if .Values.configFile.name }}
        checksum/configfile: {{ include (print $.Template.BasePath "/configmap-file.yaml") . | sha256sum }}
      {{- end }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "web-app.selectorLabels" . | nindent 8 }}
    spec:
      {{- include "web-app.pod" . | nindent 6 -}}

  {{- if or .Values.volumeClaimTemplates (eq (include "web-app.hasVolumeclaimtemplatesFromPersistence" .) "true") }}
  volumeClaimTemplates:
    {{- with .Values.volumeClaimTemplates }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if eq (include "web-app.hasVolumeclaimtemplatesFromPersistence" .) "true" }}
    {{- include "web-app.volumeclaimtemplatesFromPersistence" . | nindent 4 -}}
    {{- end }}
  {{- end }} {{/*IF ends */}}

{{- end }}
{{- end }}