{{ $namespaces := append .Values.sshClient.namespaces .Release.Namespace }}
{{ range $ns := $namespaces }}  
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "docker-dind-sshd.fullname" $ }}-ssh-dir
  labels:
    {{- include "docker-dind-sshd.labels" $ | nindent 4 }}
  namespace: {{ $ns }}

data:
  id_rsa: {{ $.Values.sshKeys.private | quote }}
  id_rsa.pub: {{ $.Values.sshKeys.public }}
  post-start.sh: |
    mkdir -p -m 600 ~/.ssh;
    cp -rL {{ $.Values.sshClient.mountPath }}/* ~/.ssh;
    chmod 400 ~/.ssh/id_rsa;
    docker context create {{ include "docker-dind-sshd.fullname" $ }} --docker "host=ssh://{{ include "docker-dind-sshd.sshUser" $ }}@{{ include "docker-dind-sshd.fullname" $ }}.{{ $.Release.Namespace }}";
    {{- if $.Values.sshClient.useContext }}
    docker context use {{ include "docker-dind-sshd.fullname" $ }};
    {{- end }}
    {{- if $.Values.sshClient.dockerLoginCmd }}
    {{ $.Values.sshClient.dockerLoginCmd }}
    {{- end }}
    {{- if $.Values.sshClient.postStartCmd }}
    {{ $.Values.sshClient.postStartCmd }}
    {{- end }}
  config: |
    Host {{ include "docker-dind-sshd.fullname" $ }}.{{ $.Release.Namespace }}
      StrictHostKeyChecking no
      UserKnownHostsFile=/dev/null
{{- end }}
