{{ if .Values.cronjob.enabled }}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "generic-app.fullname" . }}
  labels:
    {{- include "generic-app.labels" . | nindent 4 }}
spec:
  concurrencyPolicy: {{ .Values.cronjob.concurrencyPolicy }}
  {{- if .Values.cronjob.failedJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.cronjob.failedJobsHistoryLimit }}
  {{- end }}
  jobTemplate:
    spec:
      template:
        spec:
        {{- if .Values.serviceAccount.create }}
          serviceAccount: {{ include "generic-app.serviceAccountName" . }}
          serviceAccountName: {{ include "generic-app.serviceAccountName" . }}
        {{- end }}
          containers:
          - image: '{{ .Values.cronjob.image.repository }}:{{ .Values.cronjob.image.tag }}'
            imagePullPolicy: {{ .Values.cronjob.image.pullPolicy }}
            {{- with .Values.cronjob.command }}
            command:
              {{- toYaml . | nindent 14 }}
            {{- end }}
            {{- if .Values.cronjob.args }}
            args:
              {{- toYaml .Values.cronjob.args | nindent 14 }}
            {{- end }}
            name: job
          {{- if .Values.cronjob.runAsUser }}
            securityContext:
              runAsUser: {{ .Values.cronjob.runAsUser }}
          {{- end }}
          {{- if .Values.cronjob.mountEnvVars }}
            {{- if or .Values.envVars .Values.envVarsSealed }}
            envFrom:
            {{- end }}
            {{- with .Values.envVars }}
              - secretRef:
                  name: {{ include "generic-app.fullname" $ }}-env-vars
            {{- end }}
            {{- with .Values.envVarsSealed }}
              - secretRef:
                  name: {{ include "generic-app.fullname" $ }}-env-vars-sealed
            {{- end }}
          {{- end }}
          {{- if or .Values.cronjob.persistentMountPath .Values.cronjob.extraPersistentMountPath }}
            volumeMounts:
          {{- end }}
            {{- if .Values.cronjob.persistentMountPath }}
            - mountPath: {{ .Values.cronjob.persistentMountPath }}
              name: pvc-1
              readOnly: {{ .Values.cronjob.persistentMountReadOnly }}
            {{- end }}
            {{- if .Values.cronjob.extraPersistentMountPath }}
            - mountPath: {{ .Values.cronjob.extraPersistentMountPath }}
              name: pvc-2
              readOnly: {{ .Values.cronjob.extraPersistentMountReadOnly }}
            {{- end }}
            # Optional part:
            #env:
            #- name: PATENT_FOLDER
            #  value: "/tmp/data/tamm/prod/ownership/"
          {{- if .Values.cronjob.image.pullSecret }}
          imagePullSecrets:
          - name: {{ .Values.cronjob.image.pullSecret }}
          {{- end }}
          restartPolicy: {{ .Values.cronjob.restartPolicy }}
          terminationGracePeriodSeconds: 30
          {{- with .Values.cronjob.podSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 14 }}
          {{- end }}
        {{- if or .Values.cronjob.persistentMountPath .Values.cronjob.extraPersistentMountPath }}
          volumes:
        {{- end }}
        {{- if .Values.cronjob.persistentMountPath }}
          - name: pvc-1
            persistentVolumeClaim:
              claimName: {{ include "generic-app.fullname" . }}
        {{- end }}
        {{- if .Values.cronjob.extraPersistentMountPath }}
          - name: pvc-2
            persistentVolumeClaim:
              claimName: {{ include "generic-app.fullname" . }}-extra
        {{- end }}
  schedule: "{{ .Values.cronjob.schedule | toString }}"
  successfulJobsHistoryLimit: 3
{{ end }}
