apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: {{ include "generic-app.fullname" . }}
  labels:
    {{- include "generic-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: {{ .Values.deployTriggers.imageStreamChange }}
      containerNames:
      - {{ include "generic-app.fullname" . }}
      from:
        kind: ImageStreamTag
      {{- if .Values.existingImageStream.name }}
        name: {{ .Values.existingImageStream.name }}:latest
      {{- else }}
        name: {{ include "generic-app.fullname" . }}:latest
      {{- end }}
      {{- if .Values.existingImageStream.namespace }}
        namespace: {{ .Values.existingImageStream.namespace }}
      {{- end }}
    type: ImageChange
  selector:
    {{- include "generic-app.labels" . | nindent 4 }}
    deploymentconfig: {{ include "generic-app.fullname" . }}
  revisionHistoryLimit: 10
  strategy:
    activeDeadlineSeconds: 21600
    resources:
      {{- toYaml .Values.rollout.resources | nindent 6 }}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:  
      labels:
        {{- include "generic-app.labels" . | nindent 8 }}
        deploymentconfig: {{ include "generic-app.fullname" . }}
    spec:
      containers:
      - name: {{ include "generic-app.fullname" . }}
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: {{ .Values.port }}
          protocol: TCP
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        envFrom:
          - secretRef:
              name: {{ include "generic-app.fullname" . }}-env-vars
        volumeMounts:
          - mountPath: /usr/share/nginx/html
            name: secret-files
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
        - name: secret-files
          secret:
            defaultMode: 420
            # items:
            # - key: tls.crt
            #   path: jenkinsio.crt
            secretName: {{ include "generic-app.fullname" . }}-files
      securityContext:
        {{- toYaml .Values.securityContext | nindent 8 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  test: false
