apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: {{ include "single-page-app.fullname" . }}
  labels:
    {{- include "single-page-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.deployment.revisionHistoryLimit }}
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: {{ .Values.deployment.triggers.imageStreamChange }}
      containerNames:
      - {{ include "single-page-app.fullname" . }}
      from:
        kind: ImageStreamTag
        name: {{ printf "%s:%s" (include "single-page-app.fullname" .) .Values.image.tag }}
    type: ImageChange
  selector:
    {{- include "single-page-app.labels" . | nindent 4 }}
    deploymentconfig: {{ include "single-page-app.fullname" . }}
  revisionHistoryLimit: 10
  strategy:
    activeDeadlineSeconds: 21600
    resources:
      {{- toYaml .Values.rollout.resources | nindent 6 }}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:  
      labels:
        {{- include "single-page-app.labels" . | nindent 8 }}
        deploymentconfig: {{ include "single-page-app.fullname" . }}
      annotations:
        checksum/configenvvars: {{ include (print $.Template.BasePath "/secret-env-vars.yaml") . | sha256sum }}
        checksum/confignginx: {{ include (print $.Template.BasePath "/configmap-nginx.yaml") . | sha256sum }}
        checksum/configscripts: {{ include (print $.Template.BasePath "/configmap-scripts.yaml") . | sha256sum }}
    spec:
    {{- if .Values.image.repository }}
      imagePullSecrets:
        - name: {{ .Values.image.pullSecret }}
    {{- end }}
    {{- if .Values.envVars }}
      initContainers:
      - name: env-generator
        image: '{{ include "single-page-app.imageRepo" . }}:{{ .Values.image.tag }}'
        command:
          - sh
          - /tmp/scripts/envars-to-js-object
        args:
          - --dest=/tmp/data
          {{- if .Values.jsEnvFileGenerator.filename }}
          - --dest-filename={{ .Values.jsEnvFileGenerator.filename }}
          {{- end }}
          - --env-vars-filter={{ .Values.jsEnvFileGenerator.envVarsPrefix }}
          {{- if .Values.jsEnvFileGenerator.jsObjectPrefix }}
          - --js-object={{ .Values.jsEnvFileGenerator.jsObjectPrefix }}
          {{- end }}
          - --run-as=job
        volumeMounts:
          - name: data-env
            mountPath: /tmp/data
          - name: config-scripts
            mountPath: /tmp/scripts
            readOnly: true
        envFrom:
          - secretRef:
              name: {{ include "single-page-app.fullname" $ }}-env-vars
      {{- end }}
      containers:
      - name: {{ include "single-page-app.fullname" . }}
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: {{ .Values.port }}
          protocol: TCP
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        {{- with .Values.livenessProbe }}
        livenessProbe:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.readinessProbe }}
        readinessProbe:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
          - name: data-env
            mountPath: {{ .Values.jsEnvFileGenerator.mount }}
          - name: config-nginx
            mountPath: /etc/nginx/conf.d
            readOnly: true
          - name: config-scripts
            mountPath: /tmp/scripts
            readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
        - name: data-env
          emptyDir: {}
        - name: config-nginx
          configMap:
            defaultMode: 420
            name: {{ include "single-page-app.fullname" . }}-nginx
      {{- if .Values.envVars }}
        - name: config-scripts
          configMap:
            defaultMode: 420
            name: {{ include "single-page-app.fullname" . }}-scripts
            # items:
            #   - key: 
            #     path:
      {{- end }}
      securityContext:
        {{- toYaml .Values.securityContext | nindent 8 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  test: false
