{{- if or (not .Values.image.stream.name) (.Values.image.repository) }}
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: {{ include "generic-app.fullname" . }}
  labels:
    {{- include "generic-app.labels" . | nindent 4 }}
spec:
{{- if .Values.image.repository }}
  dockerImageRepository: {{ .Values.image.repository }}
  tags:
    - name: {{ .Values.image.tag | quote }}
      from:
        kind: DockerImage
        name: '{{ .Values.image.repository }}:{{ .Values.image.tag }}'
{{- else }}
  lookupPolicy:
    local: false
{{- end }}
{{- end }}