{{- if not .Values.existingImageStream.name -}}
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: {{ include "generic-app.fullname" . }}
  labels:
    {{- include "generic-app.labels" . | nindent 4 }}
spec:
  lookupPolicy:
    local: false
{{- end }}