{{- with .Values.envVarsSealed }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "generic-app.fullname" $ }}-env-vars-sealed
  labels:
    {{- include "generic-app.labels" $ | nindent 4 }}
spec:
  encryptedData:
  {{- range $key, $value:= . }}
    {{ $key }}: {{ $value | toString }}
  {{- end }}
{{- end }}
