{{- with .Values.envVarsSealed }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "generic-app.fullname" $ }}-env-vars-sealed
  {{- if has $.Values.sealScope $.Values.sealScopes }}
  annotations:
    sealedsecrets.bitnami.com/{{ $.Values.sealScope }}: "true"
  {{- end }}
  labels:
    {{- include "generic-app.labels" $ | nindent 4 }}
spec:
  encryptedData:
  {{- range $key, $value:= . }}
    {{ $key }}: {{ $value | toString }}
  {{- end }}
  template:
    data: null
    metadata:
      {{- if has $.Values.sealScope $.Values.sealScopes }}
      annotations:
        sealedsecrets.bitnami.com/{{ $.Values.sealScope }}: "true"
      {{- end }}
      creationTimestamp: null
      name: {{ include "generic-app.fullname" $ }}-env-vars-sealed
    type: Opaque
{{- end }}
