apiVersion: v1
kind: Service
metadata:
  name: {{ include "docker-dind-sshd.fullname" . }}
  labels:
    {{- include "docker-dind-sshd.labels" . | nindent 4 }}
spec:
  ports:
  - name: sshd
    port: 22
    protocol: TCP
    targetPort: {{ ternary .Values.existingDockerDaemon.port "sshd" .Values.existingDockerDaemon.enabled  }}
{{- if .Values.sshd.monitoring.enabled }}
  - name: metrics
    port: {{ .Values.sshd.monitoring.port }}
    targetPort: {{ .Values.sshd.monitoring.port }}
    protocol: TCP
{{- end }}
{{- if not  .Values.existingDockerDaemon.enabled }}
  sessionAffinity: None
  type: ClusterIP
  selector:
    {{- include "docker-dind-sshd.selectorLabels" . | nindent 4 }}
{{- end }}
{{- if .Values.existingDockerDaemon.enabled }}
---
kind: Endpoints
apiVersion: v1
metadata:
  name: {{ include "docker-dind-sshd.fullname" . }}
  labels:
    {{- include "docker-dind-sshd.labels" . | nindent 4 }}
subsets:
 - addresses:
    - ip: {{ .Values.existingDockerDaemon.ip  }}
   ports:
    - name: sshd
      port: {{ .Values.existingDockerDaemon.port }}
      protocol: TCP
{{- if .Values.sshd.monitoring.enabled }}
    - name: metrics
      port: {{ .Values.sshd.monitoring.port }}
      protocol: TCP
{{- end }}
{{- end }}