{{- if .Values.configFile.name -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "webapp.fullname" . }}-file
  labels:
    {{- include "webapp.labels" . | nindent 4 }}
data:
  {{ .Values.configFile.name }}: |
    {{ .Values.configFile.content | nindent 4 }}
{{- end }}