{{ if .Values.deployment.enabled }}
{{- if eq .Values.deployment.kind "Deployment" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "webapp.fullname" . }}
  labels:
    {{- include "webapp.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "webapp.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
      {{- if .Values.envVars }}
        checksum/configenvvars: {{ include (print $.Template.BasePath "/secret-env-vars.yaml") . | sha256sum }}
      {{- end }}
      {{- if .Values.envVarsSealed }}
        checksum/configenvvarssealed: {{ include (print $.Template.BasePath "/secret-env-vars-sealed.yaml") . | sha256sum }}
      {{- end }}
      {{- if .Values.configFile.name }}
        checksum/configfile: {{ include (print $.Template.BasePath "/configmap-file.yaml") . | sha256sum }}
      {{- end }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "webapp.selectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.image.pullSecret }}
      imagePullSecrets:
        - name: {{ .Values.image.pullSecret }}
      {{- end }}
      {{- if .Values.serviceAccount.create }}
      serviceAccount: {{ include "webapp.serviceAccountName" . }}
      serviceAccountName: {{ include "webapp.serviceAccountName" . }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
{{- if .Values.initContainers }}
      initContainers:
{{ tpl (toYaml .Values.initContainers) . | indent 8 }}
{{- end }}
      containers:
        - name: {{ include "webapp.fullname" . }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: '{{ include "webapp.imageRepo" . }}:{{ include "webapp.imageTag" . }}'
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.port }}
              protocol: TCP
        {{- if .Values.deployment.mountEnvVars }}
          {{- if or .Values.envVars .Values.envVarsSealed }}
          envFrom:
          {{- end }}
          {{- with .Values.envVars }}
            - secretRef:
                name: {{ include "webapp.fullname" $ }}-env-vars
          {{- end }}
          {{- with .Values.envVarsSealed }}
            - secretRef:
                name: {{ include "webapp.fullname" $ }}-env-vars-sealed
          {{- end }}
        {{- end }}
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 10 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 10 }}
          {{- end }}
          volumeMounts:
  {{- if .Values.volumeMounts }}
  {{ tpl (toYaml .Values.volumeMounts | indent 10) . }}
  {{- end }}
          {{- if .Values.configFile.mount }}
            - mountPath: {{ .Values.configFile.mount }}
              name: config-file
              readOnly: true
          {{- end }}
          {{- if .Values.persistence.enabled }}
            - name: pvc-1
              mountPath: {{ .Values.persistence.mount }}
          {{- end }}
          {{- if .Values.extraPersistence.enabled }}
            - name: pvc-2
              mountPath: {{ .Values.extraPersistence.mount }}
              readOnly: {{ .Values.extraPersistence.readOnly }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
{{- if .Values.volumes }}
{{ tpl (toYaml .Values.volumes | indent 8) . }}
{{- end }}
      {{- if .Values.configFile.mount }}
        - name: config-file
          configMap:
            defaultMode: 420
            name: {{ include "webapp.fullname" . }}-file
            # items:
            #   - key: {{ .Values.configFile.name }}
            #     path: {{ .Values.configFile.name }}
      {{- end }}
      {{- if .Values.persistence.enabled }}
        - name: pvc-1
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (include "webapp.fullname" .) }}
      {{- end }}
      {{- if .Values.extraPersistence.enabled }}
        - name: pvc-2
          persistentVolumeClaim:
            claimName: {{ include "webapp.fullname" . }}-extra
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
{{- end }}
