{{- with .Values.envVarsSealed }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "generic-app.fullname" $ }}-env-vars-sealed
  {{- if not (eq $.Values.sealScope "strict") }}
  annotations:
    sealedsecrets.bitnami.com/{{ $.Values.sealScope }}: "true"
    sealedsecrets.bitnami.com/scope: {{ $.Values.sealScope }}
  {{- end }}
  labels:
    {{- include "generic-app.labels" $ | nindent 4 }}
spec:
  encryptedData:
  {{- range $key, $value:= . }}
    {{ $key }}: {{ $value | toString }}
  {{- end }}
  template:
    data: null
    metadata:
      {{- if not (eq $.Values.sealScope "strict") }}
      annotations:
        sealedsecrets.bitnami.com/{{ $.Values.sealScope }}: "true"
        sealedsecrets.bitnami.com/scope: {{ $.Values.sealScope }}
      {{- end }}
      creationTimestamp: null
      name: {{ include "generic-app.fullname" $ }}-env-vars-sealed
      {{- if not (eq $.Values.sealScope "cluster-wide") }}
      namespace: {{ $.Release.Namespace }}
      {{- end }}
    type: Opaque
{{- end }}
