apiVersion: v1
kind: Service
metadata:
  name: {{ include "generic-app.fullname" . }}
  labels:
    {{- include "generic-app.labels" . | nindent 4 }}
spec:
  ports:
  - name: tcp-{{ .Values.port }}
    port: {{ .Values.port }}
    protocol: TCP
    targetPort: {{ .Values.port }}
  selector:
    {{- include "generic-app.selectorLabels" . | nindent 4 }}
    {{- if eq .Values.deployment.kind "DeploymentConfig" }}
    deploymentconfig: {{ include "generic-app.fullname" . }}
    {{- end }}
  sessionAffinity: None
  type: ClusterIP
