apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "service-proxy.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "service-proxy.labels" . | nindent 4 }}
data:
{{/* (tpl (.Files.Glob "files/envoy-modes/*.yaml").AsConfig .) | indent 2 */}}
{{- range $path, $_ := (.Files.Glob "files/envoy-modes/*.yaml") }}
  {{ trimPrefix "files/envoy-modes/" $path }}: |
    {{- tpl ($.Files.Get $path) $ | nindent 4 }}
{{ end }}