{{- with .Values.envVars }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "service-proxy.fullname" $ }}-env-vars
  labels:
    {{- include "service-proxy.labels" $ | nindent 4 }}
data:
{{- range $key, $value:= . }}
  {{ $key }}: {{ $value | toString | b64enc }}
{{- end }}
{{- end }}
