apiVersion: v1
kind: Service
metadata:
  name: {{ include "service-proxy.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "service-proxy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: web
      protocol: TCP
      name: web
    - port: {{ .Values.service.adminPort }}
      targetPort: admin
      protocol: TCP
      name: admin
  selector:
    {{- include "service-proxy.selectorLabels" . | nindent 4 }}
